---
title: "Hotel Bookings"
author: "Braden Crimmins, Jaylen Burch, Tanner Burke, Derek Fuller, Daniel Hult"
date: "2/15/2021"
output: 
  html_document:
    theme: united
    toc: TRUE
    toc_float:
      collapsed: FALSE
      smooth_scroll: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Cleaning
```{r}
library(tidyverse)
library(corrr)

hotels <- read.csv("hotel_bookings.csv")

# Variables turned into factors
# arrival_date_year
# arrival_date_month
# arrival_date_week_number
# arrival_date_day_of_month
# adults
# children
# babies
# booking_changes
# required_car_parking_spaces
# total_of_special_requests
# country
# meal
# market_segment
# distribution_channel
# customer_type
# reservation_status
# reserved_room_type
# assigned_room_type
# hotel

hotels$arrival_date_month <- as.factor(hotels$arrival_date_month)
hotels$arrival_date_year <- as.factor(hotels$arrival_date_year)
hotels$arrival_date_week_number <- as.factor(hotels$arrival_date_week_number)
hotels$arrival_date_day_of_month <- as.factor(hotels$arrival_date_day_of_month)
# hotels$children <- as.factor(hotels$children)
# hotels$adults <- as.factor(hotels$adults)
# hotels$babies <- as.factor(hotels$babies)
# hotels$previous_cancellations <- as.factor(hotels$previous_cancellations)
hotels$booking_changes <- as.factor(hotels$booking_changes)
hotels$required_car_parking_spaces <- as.factor(hotels$required_car_parking_spaces)
hotels$total_of_special_requests <- as.factor(hotels$total_of_special_requests)
hotels$country <- as.factor(hotels$country)
hotels$meal <- as.factor(hotels$meal)
hotels$market_segment <- as.factor(hotels$market_segment)
hotels$distribution_channel <- as.factor(hotels$distribution_channel)
hotels$customer_type <- as.factor(hotels$customer_type)
hotels$reservation_status <- as.factor(hotels$reservation_status)
hotels$reserved_room_type <- as.factor(hotels$reserved_room_type)
hotels$assigned_room_type <- as.factor(hotels$assigned_room_type)
hotels$hotel <- as.factor(hotels$hotel)

hotels$kids <- hotels$children + hotels$babies

hotels$totalbookings <- hotels$previous_cancellations + hotels$previous_bookings_not_canceled
hotels$propcanceled <- ifelse(hotels$totalbookings != 0, hotels$previous_cancellations/hotels$totalbookings, NA)

hotels$cancelled_morethanhalf <- as.factor(ifelse(hotels$propcanceled > 0.5, 1, 0))

str(hotels)
summary(hotels)
```

# Testing
```{r}
num_cancel <- sum(hotels$is_canceled)

hotels %>% group_by(country) %>% summarise(num_cancel = sum(is_canceled)) %>% arrange(desc(num_cancel)) %>% head(10) %>% print %>% ggplot(aes(x = country, y = num_cancel, fill= num_cancel))+ geom_col()

hotels %>% group_by(distribution_channel) %>% arrange(desc(num_cancel)) %>% head(10) %>% print %>% ggplot(aes(x = distribution_channel, y = num_cancel, fill = num_cancel)) + geom_col()

hotels %>% group_by(customer_type) %>%
  arrange(desc(num_cancel)) %>%
  ggplot(aes(x = customer_type, y = num_cancel, fill = num_cancel)) + geom_col()

hotels %>% group_by(reservation_status) %>%
  ggplot(aes(x = reservation_status, y = num_cancel)) + geom_col()

hotels %>% group_by(arrival_date_month) %>% summarise(num_cancel = sum(is_canceled)) %>% arrange(desc(num_cancel)) %>% head(12) %>% print %>% ggplot(aes(x = arrival_date_month, y = num_cancel, fill= num_cancel))+ geom_col()

hotels %>% select(is_canceled, children) %>% 
  na.omit(children) %>%
  mutate(has_child = ifelse(children != 0, 1, 0)) %>%
  group_by(has_child) %>%
  summarise(num_cancel = sum(is_canceled))

# Num Bookings w/out children = 110796
# Num Bookings w/ children = 8590
# Cancellation rate w/out child = 37%
# Cancellation rate w/ child = 36%

boxplot(propcanceled ~ is_canceled, data = hotels, na.rm = TRUE)

# table(hotels$is_canceled[is.na(hotels$propcanceled)], hotels$cancelled_morethanhalf, na.rm = TRUE)

table(hotels$is_canceled[!is.na(hotels$propcanceled)], hotels$cancelled_morethanhalf[!is.na(hotels$propcanceled)])

round(prop.table(table(hotels$is_canceled[!is.na(hotels$propcanceled)], hotels$cancelled_morethanhalf[!is.na(hotels$propcanceled)])), 3)

# Only 1/3 of your reservations by people who have made reservations before are made my people who have a history of showing up more than half the time. These people consistently show up and check in to their stay. The remaining 2/3 of reservations are made by people who have a history of cancelling. These people consistently book a reservation and then, ultimately, cancel that reservation.

# if people cancelled more than half of prev. reservations, it 
```

# Forecasting Cancellations
##### Using the historical data of past cancelations, we can create a model to forecast the likelihood of a future customer canceling.
###### Another test to check font size
```{r}
cancel <- sum(hotels$is_canceled)

hotels$arrival_week_ordered <- hotels$arrival_date_week_number


```